[package]
name = "cargo-dep-sort"
version = "0.1.0"
authors = ["Jordan Poles <jpoles1@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
regex = "1.1.5"
toml = { version = "0.5", features = ["preserve_order"] }